---
# TODO: address should be a DNS name instead of IP
listen:
  address: :9130
  metricspath: /metrics
unifi:
  address: https://192.168.1.31:8443
  username: "<<UNIFI_USERNAME>>"
  password: "<<UNIFI_PASSWORD>>"
  site: Ankhmorpork
  insecure: true
  timeout: 5s
