---
version: '2.2'

services:
  unifi:
    image: jacobalberty/unifi
    #    container_name: unifi
    init: true
    restart: always
    network_mode: host
    #    ports:
    #      - 8080:8080
    #      - 8443:8443
    #      - 3478:3478/udp
    #      - 10001:10001/udp
    volumes:
      - unifi_data:/unifi/data
      - unifi_log:/unifi/log
      - unifi_cert:/unifi/cert
      - unifi_init:/unifi/init.d
  unifilogs:
    image: bash
    depends_on:
      - unifi
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - unifi_log:/unifi/log

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock

volumes:
  unifi_data:
  unifi_log:
  unifi_cert:
  unifi_init:
  portainer_data:
