---
- name: Configure basics
  hosts: all
  gather_facts: yes
  become: yes
  any_errors_fatal: true
  roles:
#    -{ role dev-sec.os-hardening, tags: skip_ansible_lint }
    - { role: dev-sec.ssh-hardening, tags: skip_ansible_lint }
    - { role: SoInteractive.system }
    - { role: cloudalchemy.node-exporter }
  tags:
    - basics
    - security

# TODO: Better firewall management
- name: Disable firewalls (assume trusted network)
  hosts: all
  become: true
  tasks:
    - name: Trust all
      command: firewall-cmd --set-default-zone=trusted
      ignore_errors: True
      tags:
        - skip_ansible_lint
