---
- name: Install docker
  hosts: nas
  gather_facts: yes
  become: yes
  roles:
    - mongrelion.docker
  tasks:
  - name: Ensure cAdvisor is started
    docker_container:
      name: cadvisor
      image: google/cadvisor:latest
      restart_policy: always
      memory: 256m
      command: "--disable_metrics disk,tcp,udp --housekeeping_interval 5s"
      labels:
        namespace: management
      ports:
        - "8080:8080"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker:/var/lib/docker:ro"
        - "/etc/localtime:/etc/localtime:ro"
      log_driver: syslog
      log_options:
        syslog-facility: local0
        tag: cadvisor
  tags:
    - docker

- name: Configure NFS storage
  hosts: nas
  become: yes
  roles:
    - { role: geerlingguy.nfs, tags: skip_ansible_lint }
  tags:
    - nfs

- name: Configure mediacenter
  hosts: nas
  become: yes
  tasks:
    - name: Create directories
      file:
        path: /tmp/mediacenter
        state: directory
    - name: Copy docker compose file
      template:
        src: docker-compose.nas.yml.j2
        dest: /tmp/mediacenter/docker-compose.yml
    - name: Create containers
      docker_service:
        project_name: nas
        project_src: /tmp/mediacenter
