---
- name: Setup periodic jobs
  hosts: scheduler
  roles:
  - mongrelion.docker
  tasks:
  - name: Ensure cAdvisor is started
    docker_container:
      name: cadvisor
      image: google/cadvisor:latest
      restart_policy: always
      memory: 256m
      command: "--disable_metrics disk,tcp,udp --housekeeping_interval 5s"
      labels:
        namespace: management
      ports:
        - "8080:8080"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker:/var/lib/docker:ro"
        - "/etc/localtime:/etc/localtime:ro"
      log_driver: syslog
      log_options:
        syslog-facility: local0
        tag: cadvisor
  - name: "Setup autocommiter for {{ item }}"
    cron:
      cron_file: autocommiter
      user: "{{ ansible_env['SUDO_USER'] | default(ansible_user_id) }}"
      name: "{{ item }} - autocommiter"
      special_time: "daily"
      job: "docker run -it -e GH_TOKEN={{ gh_token }} -e TARGET={{ item }} paulfantom/autocommiter"
    with_items:
    - prometheus
    - alertmanager
    - node_exporter
    - blackbox_exporter
    - snmp_exporter
