---
groups:
  - name: default alert rules
    rules:
      - alert: InstanceDown
        expr: 'up{job="nodes"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
      - alert: CriticalCPULoad
        expr: '100 - (avg by (instance) (irate(node_cpu_seconds_total{job="nodes",mode="idle"}[5m])) * 100) > 96'
        for: 2m
        labels:
          severity: critical
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has Critical CPU load for more than 2 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Critical CPU load{% endraw %}"
      - alert: CriticalRAMUsage
        expr: '(1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 98'
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "{% raw %}{{ $labels.instance }} has Critical Memory Usage more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} has Critical Memory Usage{% endraw %}"
      - alert: CriticalDiskSpace
        expr: 'node_filesystem_free_bytes{job="nodes",filesystem!~"^/run(/|$)"} / node_filesystem_size_bytes{job="nodes"} < 0.05'
        for: 4m
        labels:
          severity: critical
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has less than 5% space remaining.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Critical disk space usage{% endraw %}"
      - alert: RebootRequired
        expr: "node_reboot_required > 0"
        labels:
          severity: warning
        annotations:
          description: "{% raw %}{{ $labels.instance }} requires a reboot.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - reboot required{% endraw %}"
