- name: Configure Home Assistant
  hosts: hass
  become: yes
  # roles:
  #   - antoiner77.caddy
  handlers:
    - name: restart home assistant
      systemd:
        name: 'home-assistant'
        state: started
        enabled: True
        daemon_reload: True
  tasks:
    - name: Install prerequisities
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-dev
        - python3-pip
        - python3-virtualenv
        - libffi-dev
    - name: Create Home Assistant system group
      group:
        name: homeassistant
        state: present
        system: True
    - name: Create Home Assistant system user
      user:
        name: homeassistant
        group: homeassistant
        groups: dialout
        append: False
        home: "{{ homeassistant_home }}"
        shell: "/usr/sbin/nologin"
        state: present
        system: True
    - name: Install hass in virtualenv
      pip:
        name: homeassistant
        chdir: '{{ homeassistant_home }}/home-assistant'
        extra_args: '--upgrade'
        virtualenv: "{{ homeassistant_home }}/venv"
        virtualenv_python: 'python3'
      become: True
      become_user: homeassistant
      notify: restart home assistant
    - name: Ensure Home Assistant config dir exists
      file:
        path: '{{ homeassistant_home }}/.homeassistant'
        mode: '0750'
        state: 'directory'
      become: True
      become_user: homeassistant
    - name: Configure systemd unit file
      template:
        src: 'home-assistant.service.j2'
        dest: '/etc/systemd/system/home-assistant.service'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: restart home assistant
    - name: Clone config from external repository
      become: yes
      git:
        repo: 'https://github.com/paulfantom/hass-config.git'
        dest: "{{ homeassistant_home }}/.homeassistant"
