---
- name: Setup periodic jobs
  hosts: scheduler
  roles:
  - mongrelion.docker
  tasks:
  - name: Ensure cAdvisor is started
    docker_container:
      name: cadvisor
      image: google/cadvisor:latest
      restart_policy: always
      memory: 256m
      command: "--disable_metrics disk,tcp,udp --housekeeping_interval 5s"
      labels:
        namespace: management
      ports:
        - "8080:8080"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker:/var/lib/docker:ro"
        - "/etc/localtime:/etc/localtime:ro"
      log_driver: syslog
      log_options:
        syslog-facility: local0
        tag: cadvisor
  - name: "Setup autocommiter for {{ item }}"
    cron:
      cron_file: autocommiter
      user: "{{ ansible_env['SUDO_USER'] | default(ansible_user_id) }}"
      name: "{{ item }} - autocommiter"
      special_time: "daily"
      job: "docker run -it -e GH_TOKEN={{ gh_token }} -e TARGET={{ item }} paulfantom/autocommiter"
    with_items:
    - prometheus
    - alertmanager
    - node_exporter
    - blackbox_exporter
    - snmp_exporter

  # https://vijaikumar.in/keeping-your-irccloud-client-always-connected-for-free-82db71b3cff3
  - name: Download irccloud script
    get_url:
      url: "https://raw.githubusercontent.com/vijaiaeroastro/irccloud/master/irccloud.py"
      dest: /usr/local/bin/irccloud.py
      mode: 0755      
  - name: "Setup irccloud session keeper cron job"
    cron:
      cron_file: irc
      user: "{{ ansible_env['SUDO_USER'] | default(ansible_user_id) }}"
      name: "irccloud session keeper"
      special_time: "hourly"
      job: /usr/local/bin/irccloud.py
  - name: "Configure irccloud script"
    cron:
      cron_file: irc
      env: yes
      name: "{{ item.key }}"
      value: "{{ item.value }}"
    with_dict: "{{ irccloud_credentials }}"
