#cloud-config
# vim: syntax=yaml

hostname: "<<HOSTNAME>>"
manage_etc_hosts: true

locale: "en_US.UTF-8"
timezone: "Europe/Berlin"

# resize_rootfs: false
users:
  - name: paulfantom
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/63CQz9m4DHvowZKu5/Rlczv1yUxMy25qEJ9WWG8kmJFwzwSYdnZpfQqWINZoAKo1aJuusbrrwrsCSsXS2UboI6UmZD6QXksv4CbdoQxjEmgGTyXaeLCdHqBDt7VLyxN8sQ8LBENHyQywlpfXQC3iV+QoM3DrYsnSML50WrhvRwaump7DkwbL1s3Gv3apZD0AAsxu5EwTzjd1WWIiIaYCeUe6lbhwXTTOsfmWLFMptNtDBvR3CqoV1GC4u3roh66sM3/brR2PJ7FXgt+kafpjL6IYOTsOSaLGuvxccqPVZuHKPM+8dYqybTPslK9qt3cwJ+Kz4afpVeHDIgCxxq4Z0QlKR6NZ7qtpSRFPYAya71kj/zGhLeafgmZ2flglzPiQ2+GC/Gzh2TJFY5kka1ce3zGRFgA/RE52Qgq0i0bukHrreve6YL109uCta+RiCfVvFEnPHeEY2OEPOOixZd3v4R+vbaXB8xwNM3faMo038qzmNUDHT5CJ7sJib6us9kJpTq1n/XNObIklCe0MfGrMPhDrBuf7XTPxm4H1ljgHckw/zVhvgkyyX7M9CCE3SlDHrL+gdOoILoFEG8ePMOd6ObirJg9DFlWEyIQ25DeYJHdo0mV03OWnQQVL2nI5AItDrGlH47N2vliD1Ffo7DlLq4m1Cx2z+PmUH89FrIuIcw== pawel@krupa.net.pl

package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
  - vim
  - busybox-syslogd
  - haveged
  - lsof
  - tree
  - curl
  - htop

mounts:
  - ["tmpfs", "/tmp", "tmpfs", "defaults,noatime,nosuid,size=100m", "0", "0"]
  - ["tmpfs", "/var/tmp", "tmpfs", "defaults,noatime,nosuid,size=4m", "0", "0"]
  - ["tmpfs", "/var/log", "tmpfs", "defaults,noatime,nosuid,mode=0755,size=100m", "0", "0"]
  # - ["tmpfs", "/var/spool/mqueue", "tmpfs", "defaults,noatime,nofail,nosuid,mode=0700,gid=12,size=30m", "0", "0"] # This doesn't exist on test hypriot image

write_files:
  - path: /boot/cmdline.txt
    content: "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1 elevator=deadline rootwait fsck.mode=skip fastboot rw net.ifnames=0"

runcmd:
  - "apt remove -y --purge rsyslog logrotate fake-hwclock"
  - "sed -i 's/driftfile \/var\/lib\/ntp\/ntp.drift/driftfile \/var\/tmp\/ntp.drift/' /etc/ntp.conf"
#  - "export INSTALL_K3S_SKIP_START=true && curl -sfL https://get.k3s.io | sh -"

power_state:
  mode: reboot
  message: Bye Bye
  timeout: 5
  condition: true
