#cloud-config
# vim: syntax=yaml
#
#hostname: 
manage_etc_hosts: true

timezone: "Europe/Warsaw"

resize_rootfs: true
growpart:
    mode: auto
    devices: ["/"]
    ignore_growroot_disabled: false

users:
  - name: paulfantom
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/63CQz9m4DHvowZKu5/Rlczv1yUxMy25qEJ9WWG8kmJFwzwSYdnZpfQqWINZoAKo1aJuusbrrwrsCSsXS2UboI6UmZD6QXksv4CbdoQxjEmgGTyXaeLCdHqBDt7VLyxN8sQ8LBENHyQywlpfXQC3iV+QoM3DrYsnSML50WrhvRwaump7DkwbL1s3Gv3apZD0AAsxu5EwTzjd1WWIiIaYCeUe6lbhwXTTOsfmWLFMptNtDBvR3CqoV1GC4u3roh66sM3/brR2PJ7FXgt+kafpjL6IYOTsOSaLGuvxccqPVZuHKPM+8dYqybTPslK9qt3cwJ+Kz4afpVeHDIgCxxq4Z0QlKR6NZ7qtpSRFPYAya71kj/zGhLeafgmZ2flglzPiQ2+GC/Gzh2TJFY5kka1ce3zGRFgA/RE52Qgq0i0bukHrreve6YL109uCta+RiCfVvFEnPHeEY2OEPOOixZd3v4R+vbaXB8xwNM3faMo038qzmNUDHT5CJ7sJib6us9kJpTq1n/XNObIklCe0MfGrMPhDrBuf7XTPxm4H1ljgHckw/zVhvgkyyX7M9CCE3SlDHrL+gdOoILoFEG8ePMOd6ObirJg9DFlWEyIQ25DeYJHdo0mV03OWnQQVL2nI5AItDrGlH47N2vliD1Ffo7DlLq4m1Cx2z+PmUH89FrIuIcw== pawel@krupa.net.pl

package_update: true
package_upgrade: true
package_reboot_if_required: true
